apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: atlas-api-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: atlas.example.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: atlas-api
                port:
                  number: 80
